AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de ejemplo para un grupo de seguridad de AWS

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Mi grupo de seguridad
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
